### ISSUE TITLE
Update Wrapper to Conform to API Changes

### ISSUE THREAD

**Issue by mferraco** [nessieisreal/Nessie-JavaScript-Wrapper#13]
All endpoints need verified:

ATM (should be the same)
Branch (should be the same)

Customer
Account
Bill
Deposit
Withdrawal
Transfer

**New endpoints:**
Merchants
Purchases

**Comment by vincethecoder** [comment]
Done. PR created: https://github.com/nessieisreal/nessie-javascript-wrapper/pull/14

**Comment by vincethecoder** [comment]
PR Merged.
